//! Typst + lilaq SVG plot generation for CoxMock validation results.
//!
//! Each render function generates a Typst source string using the lilaq
//! plotting library, compiles it in-memory via the typst crate, and
//! exports the result to SVG. No filesystem access — works on WASM.

use crate::validation::ValidationResult;
use typst::foundations::Bytes;
use typst::layout::PagedDocument;
use typst::syntax::{FileId, Source, VirtualPath, package::{PackageSpec, PackageVersion}};
use typst_as_lib::TypstEngine;

// Vendored package sources generated by build.rs
include!(concat!(env!("OUT_DIR"), "/typst_packages.rs"));

// Embedded fonts
static FONT_REGULAR: &[u8] = include_bytes!("fonts/NewCM10-Regular.otf");
static FONT_MATH: &[u8] = include_bytes!("fonts/NewCMMath-Regular.otf");

fn make_spec(namespace: &str, name: &str, version: &str) -> PackageSpec {
    let ver = parse_version(version);
    PackageSpec {
        namespace: namespace.into(),
        name: name.into(),
        version: ver,
    }
}

/// Build a list of Source for all vendored package .typ files.
fn vendored_sources() -> Vec<Source> {
    package_sources()
        .into_iter()
        .map(|(namespace, name, version, path, content)| {
            let spec = make_spec(namespace, name, version);
            let file_id = FileId::new(Some(spec), VirtualPath::new(path));
            Source::new(file_id, content.to_string())
        })
        .collect()
}

/// Build a list of (FileId, Bytes) for vendored package binary files (typst.toml).
fn vendored_binaries() -> Vec<(FileId, Bytes)> {
    package_binaries()
        .into_iter()
        .map(|(namespace, name, version, path, content)| {
            let spec = make_spec(namespace, name, version);
            let file_id = FileId::new(Some(spec), VirtualPath::new(path));
            (file_id, Bytes::new(content.to_vec()))
        })
        .collect()
}

fn parse_version(s: &str) -> PackageVersion {
    let parts: Vec<u32> = s.split('.').map(|p| p.parse().unwrap_or(0)).collect();
    PackageVersion {
        major: parts.first().copied().unwrap_or(0),
        minor: parts.get(1).copied().unwrap_or(0),
        patch: parts.get(2).copied().unwrap_or(0),
    }
}

/// Compile a Typst source string to SVG.
fn compile_to_svg(source: &str) -> String {
    let sources = vendored_sources();
    let binaries = vendored_binaries();

    #[cfg(debug_assertions)]
    {
        eprintln!("compile_to_svg: {} sources, {} binaries", sources.len(), binaries.len());
    }

    let engine = TypstEngine::builder()
        .main_file(source)
        .fonts([FONT_REGULAR as &[u8], FONT_MATH as &[u8]])
        .with_static_source_file_resolver(sources)
        .with_static_file_resolver(binaries)
        .build();

    let result = engine.compile::<PagedDocument>();
    match result.output {
        Ok(doc) => {
            if let Some(page) = doc.pages.first() {
                typst_svg::svg(page)
            } else {
                String::from("<svg/>")
            }
        }
        Err(e) => {
            // Include warnings for debugging
            let warnings: Vec<String> = result.warnings.iter().map(|w| format!("{:?}", w)).collect();
            panic!("Typst compilation failed: {}\nWarnings: {:?}", e, warnings);
        }
    }
}

/// Format an f64 slice as a Typst array literal.
fn fmt_array(values: &[f64]) -> String {
    let items: Vec<String> = values.iter().map(|v| format!("{:.8}", v)).collect();
    format!("({})", items.join(", "))
}

/// Render ξ(r) vs analytic comparison with error bars.
pub fn render_xi_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);
    let xi_a = fmt_array(&result.xi_analytic);
    let xi_m = fmt_array(&result.mean_xi);
    let xi_se = fmt_array(&result.stderr_xi);

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let xi-analytic = {xi_a}
#let xi-mean = {xi_m}
#let xi-stderr = {xi_se}

#lq.diagram(
  title: [CoxMock Validation: kNN Landy–Szalay],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$xi(r)$],
  lq.plot(r, xi-analytic,
    label: [Analytic $xi(r)$],
    stroke: (dash: "dashed", paint: black)),
  lq.plot(r, xi-mean,
    yerr: xi-stderr,
    label: [kNN LS mean $plus.minus sigma slash sqrt({n_mocks})$]),
)
"##,
        r = r,
        xi_a = xi_a,
        xi_m = xi_m,
        xi_se = xi_se,
        n_mocks = result.n_mocks,
    );

    compile_to_svg(&source)
}

/// Render r²ξ(r) comparison — emphasizes BAO-scale features.
pub fn render_r2xi_plot(result: &ValidationResult) -> String {
    let r2_xi_analytic: Vec<f64> = result
        .r_centers
        .iter()
        .zip(result.xi_analytic.iter())
        .map(|(&r, &xi)| r * r * xi)
        .collect();
    let r2_xi_mean: Vec<f64> = result
        .r_centers
        .iter()
        .zip(result.mean_xi.iter())
        .map(|(&r, &xi)| r * r * xi)
        .collect();
    let r2_stderr: Vec<f64> = result
        .r_centers
        .iter()
        .zip(result.stderr_xi.iter())
        .map(|(&r, &se)| r * r * se)
        .collect();

    let r = fmt_array(&result.r_centers);
    let r2xi_a = fmt_array(&r2_xi_analytic);
    let r2xi_m = fmt_array(&r2_xi_mean);
    let r2xi_se = fmt_array(&r2_stderr);

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let r2xi-analytic = {r2xi_a}
#let r2xi-mean = {r2xi_m}
#let r2xi-stderr = {r2xi_se}

#lq.diagram(
  title: [$r^2 xi(r)$ Comparison],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$r^2 xi(r)$],
  lq.plot(r, r2xi-analytic,
    label: [Analytic $r^2 xi(r)$],
    stroke: (dash: "dashed", paint: black)),
  lq.plot(r, r2xi-mean,
    yerr: r2xi-stderr,
    label: [kNN LS mean]),
)
"##,
        r = r,
        r2xi_a = r2xi_a,
        r2xi_m = r2xi_m,
        r2xi_se = r2xi_se,
    );

    compile_to_svg(&source)
}

/// Render kNN-CDFs — unique to the kNN method.
pub fn render_cdf_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);

    // Build array of CDF arrays
    let cdf_arrays: Vec<String> = result
        .knn_cdfs
        .iter()
        .map(|cdf| fmt_array(cdf))
        .collect();
    let cdfs = format!("({})", cdf_arrays.join(", "));

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let cdfs = {cdfs}

#lq.diagram(
  title: [kNN Empirical CDFs (unique to kNN method)],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$"CDF"_k (r)$],
  ..cdfs.enumerate().map(((k, cdf)) =>
    lq.plot(r, cdf, label: [$k = #(k + 1)$])
  )
)
"##,
        r = r,
        cdfs = cdfs,
    );

    compile_to_svg(&source)
}

/// Render dilution ladder variance — model-free variance estimates.
pub fn render_dilution_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);

    // Build arrays for each dilution level
    let mut level_plots = String::new();
    for (level, (xi, var)) in result
        .dilution_xi
        .iter()
        .zip(result.dilution_variance.iter())
        .enumerate()
    {
        let xi_arr = fmt_array(xi);
        let stderr: Vec<f64> = var.iter().map(|v| v.sqrt()).collect();
        let se_arr = fmt_array(&stderr);
        let r_ell = 8usize.pow(level as u32);
        let r_char = result.dilution_r_char.get(level).copied().unwrap_or(0.0);

        level_plots.push_str(&format!(
            r#"  lq.plot(r, {xi_arr},
    yerr: {se_arr},
    label: [Level {level} ($R_ell = {r_ell}$, $r_"char" = {r_char:.0}$)]),
"#,
            xi_arr = xi_arr,
            se_arr = se_arr,
            level = level,
            r_ell = r_ell,
            r_char = r_char,
        ));
    }

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}

#lq.diagram(
  title: [Dilution Ladder $hat(xi)(r) plus.minus sigma$ (model-free variance)],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$xi(r)$],
{level_plots})
"##,
        r = r,
        level_plots = level_plots,
    );

    compile_to_svg(&source)
}
