//! Typst + lilaq SVG plot generation for CoxMock validation results.
//!
//! Provides a unified plotting API used by validate.rs, the interactive
//! explorer, and the WASM web dashboard. All functions generate Typst
//! source strings using the lilaq plotting library, compiled in-memory
//! to SVG via `TypstPlotter`. No filesystem access — works on WASM.

use typst::foundations::Bytes;
use typst::layout::PagedDocument;
use typst::syntax::{FileId, Source, VirtualPath, package::{PackageSpec, PackageVersion}};
use typst_as_lib::TypstEngine;

use crate::diagnostics::{erlang_cdf, erlang_pdf};

// Vendored package sources generated by build.rs
include!(concat!(env!("OUT_DIR"), "/typst_packages.rs"));

// Embedded fonts
static FONT_REGULAR: &[u8] = include_bytes!("fonts/NewCM10-Regular.otf");
static FONT_MATH: &[u8] = include_bytes!("fonts/NewCMMath-Regular.otf");

// ---------------------------------------------------------------------------
// Infrastructure types
// ---------------------------------------------------------------------------

/// View configuration for a single plot.
#[derive(Clone, Debug)]
pub struct PlotConfig {
    pub width_cm: f64,
    pub height_cm: f64,
    pub log_x: bool,
    pub log_y: bool,
    pub x_range: Option<(f64, f64)>,
    pub y_range: Option<(f64, f64)>,
}

impl Default for PlotConfig {
    fn default() -> Self {
        Self {
            width_cm: 16.0,
            height_cm: 11.0,
            log_x: false,
            log_y: false,
            x_range: None,
            y_range: None,
        }
    }
}

/// All computed arrays needed for plotting, populated from validate.rs
/// after the mock loop. Shared data contract between validate.rs, explorer,
/// and WASM.
pub struct PlotData {
    pub r_centers: Vec<f64>,
    pub r_smooth: Vec<f64>,
    pub xi_smooth: Vec<f64>,
    pub mean_xi: Vec<f64>,
    pub std_xi: Vec<f64>,
    pub bias_sigma: Vec<f64>,
    pub all_xi: Vec<Vec<f64>>,
    pub line_length: f64,
    pub cdf_rr_summary: Option<crate::ladder::KnnCdfSummary>,
    pub cdf_nbar: f64,
    // Corrfunc reference data (all Optional so explorer works without it)
    pub corrfunc_mean_xi: Option<Vec<f64>>,
    pub corrfunc_std_xi: Option<Vec<f64>>,
    pub corrfunc_all_xi: Option<Vec<Vec<f64>>>,
    pub knn_times: Option<Vec<f64>>,
    pub corrfunc_times: Option<Vec<f64>>,
    pub level_tags: Option<Vec<usize>>,
}

/// Caches vendored typst sources for fast repeated compilation.
pub struct TypstPlotter {
    sources: Vec<Source>,
    binaries: Vec<(FileId, Bytes)>,
}

impl TypstPlotter {
    /// Parse vendored sources/binaries once for reuse across renders.
    pub fn new() -> Self {
        Self {
            sources: vendored_sources(),
            binaries: vendored_binaries(),
        }
    }

    /// Compile a Typst source string to SVG.
    pub fn render(&self, typst_source: &str) -> String {
        let engine = TypstEngine::builder()
            .main_file(typst_source)
            .fonts([FONT_REGULAR as &[u8], FONT_MATH as &[u8]])
            .with_static_source_file_resolver(self.sources.clone())
            .with_static_file_resolver(self.binaries.clone())
            .build();

        let result = engine.compile::<PagedDocument>();
        match result.output {
            Ok(doc) => {
                if let Some(page) = doc.pages.first() {
                    typst_svg::svg(page)
                } else {
                    String::from("<svg/>")
                }
            }
            Err(e) => {
                let warnings: Vec<String> =
                    result.warnings.iter().map(|w| format!("{:?}", w)).collect();
                panic!("Typst compilation failed: {}\nWarnings: {:?}", e, warnings);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Typst internals — vendored source loading
// ---------------------------------------------------------------------------

fn make_spec(namespace: &str, name: &str, version: &str) -> PackageSpec {
    let ver = parse_version(version);
    PackageSpec {
        namespace: namespace.into(),
        name: name.into(),
        version: ver,
    }
}

fn vendored_sources() -> Vec<Source> {
    package_sources()
        .into_iter()
        .map(|(namespace, name, version, path, content)| {
            let spec = make_spec(namespace, name, version);
            let file_id = FileId::new(Some(spec), VirtualPath::new(path));
            Source::new(file_id, content.to_string())
        })
        .collect()
}

fn vendored_binaries() -> Vec<(FileId, Bytes)> {
    package_binaries()
        .into_iter()
        .map(|(namespace, name, version, path, content)| {
            let spec = make_spec(namespace, name, version);
            let file_id = FileId::new(Some(spec), VirtualPath::new(path));
            (file_id, Bytes::new(content.to_vec()))
        })
        .collect()
}

fn parse_version(s: &str) -> PackageVersion {
    let parts: Vec<u32> = s.split('.').map(|p| p.parse().unwrap_or(0)).collect();
    PackageVersion {
        major: parts.first().copied().unwrap_or(0),
        minor: parts.get(1).copied().unwrap_or(0),
        patch: parts.get(2).copied().unwrap_or(0),
    }
}

// ---------------------------------------------------------------------------
// Typst source helpers
// ---------------------------------------------------------------------------

/// Format an f64 slice as a Typst array literal.
fn fmt_array(values: &[f64]) -> String {
    let items: Vec<String> = values.iter().map(|v| format!("{:.8}", v)).collect();
    format!("({})", items.join(", "))
}

/// Format scale parameter for lq.diagram.
fn fmt_scale(log: bool) -> &'static str {
    if log { "\"log\"" } else { "\"linear\"" }
}

/// Format axis limit for lq.diagram.
fn fmt_lim(range: Option<(f64, f64)>) -> String {
    match range {
        Some((lo, hi)) => format!("({:.8}, {:.8})", lo, hi),
        None => "auto".to_string(),
    }
}

/// Emit the standard typst preamble.
fn preamble(config: &PlotConfig) -> String {
    format!(
        r##"#set page(width: {w}cm, height: {h}cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq
#let steelblue = rgb("#4682B4")
#let crimson = rgb("#DC143C")
#let seagreen = rgb("#2E8B57")
#let darkorange = rgb("#FF8C00")
#let level-colors = (steelblue, seagreen, darkorange, crimson)
"##,
        w = config.width_cm,
        h = config.height_cm,
    )
}

/// Emit diagram options for scales and limits.
fn diagram_opts(config: &PlotConfig) -> String {
    format!(
        "xscale: {xs}, yscale: {ys}, xlim: {xl}, ylim: {yl}",
        xs = fmt_scale(config.log_x),
        ys = fmt_scale(config.log_y),
        xl = fmt_lim(config.x_range),
        yl = fmt_lim(config.y_range),
    )
}

// ---------------------------------------------------------------------------
// Render functions — each returns Typst source (not SVG)
// ---------------------------------------------------------------------------

/// 1. ξ(r) comparison: error band + mean line + analytic dashed + optional vline
pub fn render_xi_comparison(data: &PlotData, config: &PlotConfig) -> String {
    let n = data.r_centers.len();
    let mut src = preamble(config);

    // Data arrays
    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));
    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let xi-smooth = {}\n", fmt_array(&data.xi_smooth)));
    src.push_str(&format!("#let mean-xi = {}\n", fmt_array(&data.mean_xi)));

    let lower: Vec<f64> = (0..n).map(|i| data.mean_xi[i] - data.std_xi[i]).collect();
    let upper: Vec<f64> = (0..n).map(|i| data.mean_xi[i] + data.std_xi[i]).collect();
    src.push_str(&format!("#let lower = {}\n", fmt_array(&lower)));
    src.push_str(&format!("#let upper = {}\n", fmt_array(&upper)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [CoxMock: $xi(r)$ Recovery],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$xi(r)$],\n  {},\n",
        diagram_opts(config),
    ));

    // Per-level or single band
    if let Some(ref tags) = data.level_tags {
        let max_level = *tags.iter().max().unwrap_or(&0);
        for level in 0..=max_level {
            let indices: Vec<usize> = (0..n).filter(|&i| tags[i] == level).collect();
            if indices.is_empty() { continue; }
            let r_l: Vec<f64> = indices.iter().map(|&i| data.r_centers[i]).collect();
            let lo: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i] - data.std_xi[i]).collect();
            let hi: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i] + data.std_xi[i]).collect();
            let xi_l: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i]).collect();
            src.push_str(&format!(
                "  lq.fill-between({}, {}, {},\n    fill: level-colors.at({}).lighten(80%),\n    stroke: none),\n",
                fmt_array(&r_l), fmt_array(&lo), fmt_array(&hi), level,
            ));
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (paint: level-colors.at({}), thickness: 2pt),\n    label: [Level {}]),\n",
                fmt_array(&r_l), fmt_array(&xi_l), level, level,
            ));
        }
    } else {
        src.push_str("  lq.fill-between(r, lower, upper,\n    fill: steelblue.lighten(80%),\n    stroke: none,\n    label: [kNN LS $plus.minus 1 sigma$]),\n");
        src.push_str("  lq.plot(r, mean-xi,\n    stroke: (paint: steelblue, thickness: 2pt)),\n");
    }

    // Analytic
    src.push_str("  lq.plot(r-smooth, xi-smooth,\n    stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt),\n    label: [Analytic $xi(r)$]),\n");

    // Reference line
    src.push_str(&format!(
        "  lq.vlines({:.8},\n    stroke: (dash: \"dotted\", paint: gray, thickness: 0.8pt)),\n",
        data.line_length,
    ));

    // Corrfunc overlay
    if let (Some(cf_mean), Some(cf_std)) = (&data.corrfunc_mean_xi, &data.corrfunc_std_xi) {
        src.push_str(&format!(
            "  lq.plot({}, {},\n    yerr: {},\n    stroke: none, mark: \"o\", mark-size: 4pt,\n    color: crimson,\n    label: [Corrfunc $plus.minus 1 sigma$]),\n",
            fmt_array(&data.r_centers), fmt_array(cf_mean), fmt_array(cf_std),
        ));
    }

    src.push_str(")\n");
    src
}

/// 2. Residuals: scatter + reference lines at 0, ±2σ
pub fn render_residuals(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);

    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));
    src.push_str(&format!("#let bias = {}\n", fmt_array(&data.bias_sigma)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [Estimator Bias],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$(hat(xi) - xi_\"true\") slash sigma_\"mean\"$],\n  {},\n",
        diagram_opts(config),
    ));
    src.push_str("  lq.plot(r, bias,\n    stroke: none, mark: \"o\", mark-size: 4pt,\n    color: steelblue,\n    label: [Bias$/sigma$]),\n");
    src.push_str("  lq.hlines(0,\n    stroke: (dash: \"dashed\", paint: black, thickness: 0.8pt)),\n");
    src.push_str("  lq.hlines(2,\n    stroke: (dash: \"dashed\", paint: crimson, thickness: 0.7pt)),\n");
    src.push_str("  lq.hlines(-2,\n    stroke: (dash: \"dashed\", paint: crimson, thickness: 0.7pt)),\n");
    src.push_str(")\n");
    src
}

/// 3. r²ξ(r) comparison
pub fn render_r2xi(data: &PlotData, config: &PlotConfig) -> String {
    let n = data.r_centers.len();
    let mut src = preamble(config);

    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));

    let r2xi_analytic: Vec<f64> = data.r_smooth.iter()
        .zip(data.xi_smooth.iter())
        .map(|(&r, &xi)| r * r * xi)
        .collect();
    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let r2xi-analytic = {}\n", fmt_array(&r2xi_analytic)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [$r^2 xi(r)$ Comparison],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$r^2 xi(r)$ #h(0.3em) $[$h$\"\"^(-2)$ Mpc$\"\"^2]$],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(ref tags) = data.level_tags {
        let max_level = *tags.iter().max().unwrap_or(&0);
        for level in 0..=max_level {
            let indices: Vec<usize> = (0..n).filter(|&i| tags[i] == level).collect();
            if indices.is_empty() { continue; }
            let r_l: Vec<f64> = indices.iter().map(|&i| data.r_centers[i]).collect();
            let lo: Vec<f64> = indices.iter().map(|&i| data.r_centers[i].powi(2) * (data.mean_xi[i] - data.std_xi[i])).collect();
            let hi: Vec<f64> = indices.iter().map(|&i| data.r_centers[i].powi(2) * (data.mean_xi[i] + data.std_xi[i])).collect();
            let r2xi_l: Vec<f64> = indices.iter().map(|&i| data.r_centers[i].powi(2) * data.mean_xi[i]).collect();
            src.push_str(&format!(
                "  lq.fill-between({}, {}, {},\n    fill: level-colors.at({}).lighten(80%),\n    stroke: none),\n",
                fmt_array(&r_l), fmt_array(&lo), fmt_array(&hi), level,
            ));
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (paint: level-colors.at({}), thickness: 2pt),\n    label: [Level {}]),\n",
                fmt_array(&r_l), fmt_array(&r2xi_l), level, level,
            ));
        }
    } else {
        let r2xi_mean: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * data.mean_xi[i]).collect();
        let r2xi_lower: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * (data.mean_xi[i] - data.std_xi[i])).collect();
        let r2xi_upper: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * (data.mean_xi[i] + data.std_xi[i])).collect();
        src.push_str(&format!("#let r2xi-mean = {}\n", fmt_array(&r2xi_mean)));
        src.push_str(&format!("#let r2xi-lower = {}\n", fmt_array(&r2xi_lower)));
        src.push_str(&format!("#let r2xi-upper = {}\n", fmt_array(&r2xi_upper)));
        src.push_str("  lq.fill-between(r, r2xi-lower, r2xi-upper,\n    fill: steelblue.lighten(80%),\n    stroke: none),\n");
        src.push_str("  lq.plot(r, r2xi-mean,\n    stroke: (paint: steelblue, thickness: 2pt),\n    label: [kNN LS]),\n");
    }

    src.push_str("  lq.plot(r-smooth, r2xi-analytic,\n    stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt),\n    label: [Analytic]),\n");
    src.push_str(&format!(
        "  lq.vlines({:.8},\n    stroke: (dash: \"dotted\", paint: gray, thickness: 0.8pt)),\n",
        data.line_length,
    ));

    // Corrfunc overlay
    if let (Some(cf_mean), Some(cf_std)) = (&data.corrfunc_mean_xi, &data.corrfunc_std_xi) {
        let r2cf_mean: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * cf_mean[i]).collect();
        let r2cf_err: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * cf_std[i]).collect();
        src.push_str(&format!(
            "  lq.plot({}, {},\n    yerr: {},\n    stroke: none, mark: \"o\", mark-size: 4pt,\n    color: crimson,\n    label: [Corrfunc]),\n",
            fmt_array(&data.r_centers), fmt_array(&r2cf_mean), fmt_array(&r2cf_err),
        ));
    }

    src.push_str(")\n");
    src
}

/// 4. CDF comparison: measured vs Erlang for each k
pub fn render_cdf_comparison(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);
    let colors = ["steelblue", "crimson", "seagreen", "darkorange"];

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [kNN-CDF: Random Catalog vs Erlang],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$\"CDF\"_k (r)$],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(ref cdf) = data.cdf_rr_summary {
        let r_arr = fmt_array(&cdf.r_values);
        for (idx, &k) in cdf.k_values.iter().enumerate() {
            let color = colors[idx % colors.len()];
            let measured = fmt_array(&cdf.cdf_mean[idx]);
            let erlang_vals: Vec<f64> = cdf.r_values.iter()
                .map(|&r| erlang_cdf(k, r, data.cdf_nbar))
                .collect();
            let erlang_arr = fmt_array(&erlang_vals);
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (paint: {}, thickness: 2pt),\n    label: [$k = {}$ measured]),\n",
                r_arr, measured, color, k,
            ));
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (dash: \"dashed\", paint: black, thickness: 1pt)),\n",
                r_arr, erlang_arr,
            ));
        }
    }

    src.push_str(")\n");
    src
}

/// 5. Peaked CDF (PDF): numerical dCDF/dr and analytic Erlang PDF
pub fn render_peaked_cdf(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);
    let colors = ["steelblue", "crimson", "seagreen", "darkorange"];

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [kNN-PDF: $d$CDF$/d r$ (peaked CDF)],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$d\"CDF\"_k slash d r$],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(ref cdf) = data.cdf_rr_summary {
        let r = &cdf.r_values;
        let nr = r.len();
        let r_arr = fmt_array(r);

        for (idx, &k) in cdf.k_values.iter().enumerate() {
            let color = colors[idx % colors.len()];
            let measured = &cdf.cdf_mean[idx];

            // Numerical derivative via central differences
            let mut pdf = vec![0.0; nr];
            if nr >= 3 {
                pdf[0] = (measured[1] - measured[0]) / (r[1] - r[0]);
                for i in 1..nr - 1 {
                    pdf[i] = (measured[i + 1] - measured[i - 1]) / (r[i + 1] - r[i - 1]);
                }
                pdf[nr - 1] = (measured[nr - 1] - measured[nr - 2]) / (r[nr - 1] - r[nr - 2]);
            }

            let analytic: Vec<f64> = r.iter().map(|&ri| erlang_pdf(k, ri, data.cdf_nbar)).collect();

            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (paint: {}, thickness: 2pt),\n    label: [$k = {}$ measured]),\n",
                r_arr, fmt_array(&pdf), color, k,
            ));
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (dash: \"dashed\", paint: black, thickness: 1pt)),\n",
                r_arr, fmt_array(&analytic),
            ));
        }
    }

    src.push_str(")\n");
    src
}

/// 6. Individual mock realizations overlaid
pub fn render_individual_mocks(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);

    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));
    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let xi-smooth = {}\n", fmt_array(&data.xi_smooth)));
    src.push_str(&format!("#let mean-xi = {}\n", fmt_array(&data.mean_xi)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [Individual Mock Realizations],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$xi(r)$],\n  {},\n",
        diagram_opts(config),
    ));

    // Individual mocks in light blue
    for xi in &data.all_xi {
        src.push_str(&format!(
            "  lq.plot(r, {},\n    stroke: (paint: steelblue.lighten(60%), thickness: 0.7pt)),\n",
            fmt_array(xi),
        ));
    }

    // Bold mean
    src.push_str("  lq.plot(r, mean-xi,\n    stroke: (paint: steelblue, thickness: 2.5pt),\n    label: [Mean]),\n");
    // Analytic dashed
    src.push_str("  lq.plot(r-smooth, xi-smooth,\n    stroke: (dash: \"dashed\", paint: black, thickness: 2pt),\n    label: [Analytic]),\n");
    // Reference line
    src.push_str(&format!(
        "  lq.vlines({:.8},\n    stroke: (dash: \"dotted\", paint: gray, thickness: 0.8pt)),\n",
        data.line_length,
    ));

    src.push_str(")\n");
    src
}

/// 7. ξ(r) overlay: kNN band + Corrfunc scatter + analytic
pub fn render_xi_corrfunc_overlay(data: &PlotData, config: &PlotConfig) -> String {
    let n = data.r_centers.len();
    let mut src = preamble(config);

    let lower: Vec<f64> = (0..n).map(|i| data.mean_xi[i] - data.std_xi[i]).collect();
    let upper: Vec<f64> = (0..n).map(|i| data.mean_xi[i] + data.std_xi[i]).collect();

    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));
    src.push_str(&format!("#let mean-xi = {}\n", fmt_array(&data.mean_xi)));
    src.push_str(&format!("#let lower = {}\n", fmt_array(&lower)));
    src.push_str(&format!("#let upper = {}\n", fmt_array(&upper)));
    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let xi-smooth = {}\n", fmt_array(&data.xi_smooth)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [$xi(r)$: kNN vs Corrfunc],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$xi(r)$],\n  {},\n",
        diagram_opts(config),
    ));

    src.push_str("  lq.fill-between(r, lower, upper,\n    fill: steelblue.lighten(80%),\n    stroke: none),\n");
    src.push_str("  lq.plot(r, mean-xi,\n    stroke: (paint: steelblue, thickness: 2pt),\n    label: [kNN LS $plus.minus 1 sigma$]),\n");

    if let (Some(cf_mean), Some(cf_std)) = (&data.corrfunc_mean_xi, &data.corrfunc_std_xi) {
        src.push_str(&format!(
            "  lq.plot({}, {},\n    yerr: {},\n    stroke: none, mark: \"o\", mark-size: 4pt,\n    color: crimson,\n    label: [Corrfunc $plus.minus 1 sigma$]),\n",
            fmt_array(&data.r_centers), fmt_array(cf_mean), fmt_array(cf_std),
        ));
    }

    src.push_str("  lq.plot(r-smooth, xi-smooth,\n    stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt),\n    label: [Analytic $xi(r)$]),\n");
    src.push_str(&format!(
        "  lq.vlines({:.8},\n    stroke: (dash: \"dotted\", paint: gray, thickness: 0.8pt)),\n",
        data.line_length,
    ));

    src.push_str(")\n");
    src
}

/// 8. ξ ratio: kNN / Corrfunc with ±2% reference
pub fn render_xi_ratio(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [$xi$ Ratio: kNN / Corrfunc],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$xi_\"kNN\" slash xi_\"Corrfunc\"$],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(cf_mean) = &data.corrfunc_mean_xi {
        let ratio: Vec<f64> = data.mean_xi.iter()
            .zip(cf_mean.iter())
            .map(|(&knn, &cf)| if cf.abs() > 1e-15 { knn / cf } else { 1.0 })
            .collect();
        src.push_str(&format!(
            "  lq.plot({}, {},\n    stroke: none, mark: \"o\", mark-size: 4.5pt,\n    color: steelblue,\n    label: [$xi_\"kNN\" slash xi_\"Corrfunc\"$]),\n",
            fmt_array(&data.r_centers), fmt_array(&ratio),
        ));
    }

    src.push_str("  lq.hlines(1,\n    stroke: (dash: \"dashed\", paint: black, thickness: 1pt)),\n");
    src.push_str("  lq.hlines(1.02,\n    stroke: (dash: \"dashed\", paint: crimson, thickness: 0.7pt)),\n");
    src.push_str("  lq.hlines(0.98,\n    stroke: (dash: \"dashed\", paint: crimson, thickness: 0.7pt)),\n");

    src.push_str(")\n");
    src
}

/// 9. Timing comparison: kNN vs Corrfunc
pub fn render_timing(data: &PlotData, config: &PlotConfig) -> String {
    let mut src = preamble(config);

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [Wall-Clock Time per Mock],\n  xlabel: [Mock index],\n  ylabel: [Time (s)],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(knn_t) = &data.knn_times {
        let indices: Vec<f64> = (0..knn_t.len()).map(|i| i as f64).collect();
        src.push_str(&format!(
            "  lq.plot({}, {},\n    stroke: none, mark: \"o\", mark-size: 5pt,\n    color: steelblue,\n    label: [kNN]),\n",
            fmt_array(&indices), fmt_array(knn_t),
        ));
    }

    if let Some(cf_t) = &data.corrfunc_times {
        let indices: Vec<f64> = (0..cf_t.len()).map(|i| i as f64).collect();
        src.push_str(&format!(
            "  lq.plot({}, {},\n    stroke: none, mark: \"o\", mark-size: 5pt,\n    color: crimson,\n    label: [Corrfunc]),\n",
            fmt_array(&indices), fmt_array(cf_t),
        ));
    }

    src.push_str(")\n");
    src
}

/// 10. Dilution levels: per-level bands + lines + analytic
pub fn render_dilution_levels(data: &PlotData, config: &PlotConfig) -> String {
    let n = data.r_centers.len();
    let mut src = preamble(config);

    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let xi-smooth = {}\n", fmt_array(&data.xi_smooth)));

    src.push_str(&format!(
        "\n#lq.diagram(\n  title: [Dilution Ladder: Per-Level $xi(r)$],\n  xlabel: [$r$ #h(0.3em) $[$h$\"\"^(-1)$ Mpc$]$],\n  ylabel: [$xi(r)$],\n  {},\n",
        diagram_opts(config),
    ));

    if let Some(ref tags) = data.level_tags {
        let max_level = *tags.iter().max().unwrap_or(&0);
        for level in 0..=max_level {
            let indices: Vec<usize> = (0..n).filter(|&i| tags[i] == level).collect();
            if indices.is_empty() { continue; }
            let r_l: Vec<f64> = indices.iter().map(|&i| data.r_centers[i]).collect();
            let lo: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i] - data.std_xi[i]).collect();
            let hi: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i] + data.std_xi[i]).collect();
            let xi_l: Vec<f64> = indices.iter().map(|&i| data.mean_xi[i]).collect();
            src.push_str(&format!(
                "  lq.fill-between({}, {}, {},\n    fill: level-colors.at({}).lighten(85%),\n    stroke: none),\n",
                fmt_array(&r_l), fmt_array(&lo), fmt_array(&hi), level,
            ));
            src.push_str(&format!(
                "  lq.plot({}, {},\n    stroke: (paint: level-colors.at({}), thickness: 2pt),\n    label: [Level {}]),\n",
                fmt_array(&r_l), fmt_array(&xi_l), level, level,
            ));
        }
    }

    src.push_str("  lq.plot(r-smooth, xi-smooth,\n    stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt),\n    label: [Analytic]),\n");
    src.push_str(&format!(
        "  lq.vlines({:.8},\n    stroke: (dash: \"dotted\", paint: gray, thickness: 0.8pt)),\n",
        data.line_length,
    ));

    src.push_str(")\n");
    src
}

/// 11. Summary 2×2 figure: ξ, r²ξ, residuals, CDF
pub fn render_summary_figure(data: &PlotData, config: &PlotConfig) -> String {
    let n = data.r_centers.len();
    let mut src = preamble(config);

    // Data arrays shared across panels
    src.push_str(&format!("#let r = {}\n", fmt_array(&data.r_centers)));
    src.push_str(&format!("#let r-smooth = {}\n", fmt_array(&data.r_smooth)));
    src.push_str(&format!("#let xi-smooth = {}\n", fmt_array(&data.xi_smooth)));
    src.push_str(&format!("#let mean-xi = {}\n", fmt_array(&data.mean_xi)));
    src.push_str(&format!("#let bias = {}\n", fmt_array(&data.bias_sigma)));

    let lower: Vec<f64> = (0..n).map(|i| data.mean_xi[i] - data.std_xi[i]).collect();
    let upper: Vec<f64> = (0..n).map(|i| data.mean_xi[i] + data.std_xi[i]).collect();
    src.push_str(&format!("#let lower = {}\n", fmt_array(&lower)));
    src.push_str(&format!("#let upper = {}\n", fmt_array(&upper)));

    let r2xi_mean: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * data.mean_xi[i]).collect();
    let r2xi_lower: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * (data.mean_xi[i] - data.std_xi[i])).collect();
    let r2xi_upper: Vec<f64> = (0..n).map(|i| data.r_centers[i].powi(2) * (data.mean_xi[i] + data.std_xi[i])).collect();
    let r2xi_analytic: Vec<f64> = data.r_smooth.iter().zip(data.xi_smooth.iter()).map(|(&r, &xi)| r * r * xi).collect();
    src.push_str(&format!("#let r2xi-mean = {}\n", fmt_array(&r2xi_mean)));
    src.push_str(&format!("#let r2xi-lower = {}\n", fmt_array(&r2xi_lower)));
    src.push_str(&format!("#let r2xi-upper = {}\n", fmt_array(&r2xi_upper)));
    src.push_str(&format!("#let r2xi-analytic = {}\n", fmt_array(&r2xi_analytic)));

    src.push_str("\n#show: lq.layout\n");
    src.push_str("#grid(columns: 2, column-gutter: 1.2em, row-gutter: 1em,\n");

    // Panel (a): ξ(r)
    src.push_str("  lq.diagram(\n    title: [(a) $xi(r)$],\n    xlabel: [$r$ #h(0.2em) $[$h$\"\"^(-1)$ Mpc$]$],\n    ylabel: [$xi(r)$],\n");
    src.push_str("    lq.fill-between(r, lower, upper,\n      fill: steelblue.lighten(80%),\n      stroke: none,\n      label: [kNN LS]),\n");
    src.push_str("    lq.plot(r, mean-xi,\n      stroke: (paint: steelblue, thickness: 2pt)),\n");
    src.push_str("    lq.plot(r-smooth, xi-smooth,\n      stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt),\n      label: [Analytic]),\n");
    src.push_str("  ),\n");

    // Panel (b): r²ξ(r)
    src.push_str("  lq.diagram(\n    title: [(b) $r^2 xi(r)$],\n    xlabel: [$r$ #h(0.2em) $[$h$\"\"^(-1)$ Mpc$]$],\n    ylabel: [$r^2 xi(r)$],\n");
    src.push_str("    lq.fill-between(r, r2xi-lower, r2xi-upper,\n      fill: steelblue.lighten(80%),\n      stroke: none),\n");
    src.push_str("    lq.plot(r, r2xi-mean,\n      stroke: (paint: steelblue, thickness: 2pt)),\n");
    src.push_str("    lq.plot(r-smooth, r2xi-analytic,\n      stroke: (dash: \"dashed\", paint: black, thickness: 1.5pt)),\n");
    src.push_str("  ),\n");

    // Panel (c): Residuals
    src.push_str("  lq.diagram(\n    title: [(c) Bias / $sigma_\"mean\"$],\n    xlabel: [$r$ #h(0.2em) $[$h$\"\"^(-1)$ Mpc$]$],\n    ylabel: [$(hat(xi) - xi_\"true\") slash sigma$],\n");
    src.push_str("    lq.plot(r, bias,\n      stroke: none, mark: \"o\", mark-size: 3.5pt,\n      color: steelblue),\n");
    src.push_str("    lq.hlines(0,\n      stroke: (dash: \"dashed\", paint: black, thickness: 0.8pt)),\n");
    src.push_str("    lq.hlines(2,\n      stroke: (dash: \"dashed\", paint: crimson, thickness: 0.6pt)),\n");
    src.push_str("    lq.hlines(-2,\n      stroke: (dash: \"dashed\", paint: crimson, thickness: 0.6pt)),\n");
    src.push_str("  ),\n");

    // Panel (d): CDF
    src.push_str("  lq.diagram(\n    title: [(d) kNN-CDF vs Erlang (RR)],\n    xlabel: [$r$ #h(0.2em) $[$h$\"\"^(-1)$ Mpc$]$],\n    ylabel: [$\"CDF\"_k (r)$],\n");
    if let Some(ref cdf) = data.cdf_rr_summary {
        let colors_arr = ["steelblue", "crimson", "seagreen", "darkorange"];
        let r_arr = fmt_array(&cdf.r_values);
        for (idx, &k) in cdf.k_values.iter().enumerate() {
            let color = colors_arr[idx % colors_arr.len()];
            let measured = fmt_array(&cdf.cdf_mean[idx]);
            let erlang_vals: Vec<f64> = cdf.r_values.iter()
                .map(|&r| erlang_cdf(k, r, data.cdf_nbar))
                .collect();
            src.push_str(&format!(
                "    lq.plot({}, {},\n      stroke: (paint: {}, thickness: 1.5pt),\n      label: [$k = {}$]),\n",
                r_arr, measured, color, k,
            ));
            src.push_str(&format!(
                "    lq.plot({}, {},\n      stroke: (dash: \"dashed\", paint: black, thickness: 0.8pt)),\n",
                r_arr, fmt_array(&erlang_vals),
            ));
        }
    }
    src.push_str("  ),\n");

    src.push_str(")\n");
    src
}

/// Explorer 4×2 summary: 8 panels with independent view states.
pub fn render_explorer_summary(data: &PlotData, panel_configs: &[PlotConfig; 8]) -> String {
    // Use wider page for the 4×2 layout
    let mut src = format!(
        r##"#set page(width: 36cm, height: 26cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq
#let steelblue = rgb("#4682B4")
#let crimson = rgb("#DC143C")
#let seagreen = rgb("#2E8B57")
#let darkorange = rgb("#FF8C00")
#let level-colors = (steelblue, seagreen, darkorange, crimson)
"##
    );

    // Generate each panel's source inline within the grid
    let panel_fns: [fn(&PlotData, &PlotConfig) -> String; 8] = [
        render_xi_comparison,
        render_residuals,
        render_r2xi,
        render_cdf_comparison,
        render_peaked_cdf,
        render_individual_mocks,
        render_xi_ratio,
        render_timing,
    ];
    let labels = ["(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"];

    // We need to extract just the diagram portion from each render function.
    // Instead, build the grid directly with diagram calls.
    src.push_str("\n#show: lq.layout\n");
    src.push_str("#grid(columns: 4, column-gutter: 1em, row-gutter: 1em,\n");

    for (i, (panel_fn, label)) in panel_fns.iter().zip(labels.iter()).enumerate() {
        // Generate the full source for each panel, but we only need the diagram.
        // Extract the lq.diagram(...) call from the rendered source.
        let panel_src = panel_fn(data, &panel_configs[i]);
        // Find the diagram block — it starts after the preamble
        if let Some(diag_start) = panel_src.find("#lq.diagram(") {
            let diag = &panel_src[diag_start..];
            // Replace the title with the label prefix
            let labeled = diag.replacen("title:", &format!("// {}\n    title:", label), 1);
            src.push_str("  ");
            src.push_str(&labeled);
            // Remove trailing newline and add comma
            if src.ends_with('\n') {
                src.pop();
            }
            src.push_str(",\n");
        }
    }

    src.push_str(")\n");
    src
}

// ---------------------------------------------------------------------------
// Legacy API: compile_to_svg for backward compatibility with existing callers
// ---------------------------------------------------------------------------

/// Compile a Typst source string to SVG (standalone, no caching).
/// Prefer `TypstPlotter::render()` for repeated use.
pub fn compile_to_svg(source: &str) -> String {
    let plotter = TypstPlotter::new();
    plotter.render(source)
}

// ---------------------------------------------------------------------------
// Legacy render functions for ValidationResult (used by examples, WASM)
// ---------------------------------------------------------------------------

use crate::validation::ValidationResult;

/// Render ξ(r) vs analytic comparison with error bars.
pub fn render_xi_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);
    let xi_a = fmt_array(&result.xi_analytic);
    let xi_m = fmt_array(&result.mean_xi);
    let xi_se = fmt_array(&result.stderr_xi);

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let xi-analytic = {xi_a}
#let xi-mean = {xi_m}
#let xi-stderr = {xi_se}

#lq.diagram(
  title: [CoxMock Validation: kNN Landy–Szalay],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$xi(r)$],
  lq.plot(r, xi-analytic,
    label: [Analytic $xi(r)$],
    stroke: (dash: "dashed", paint: black)),
  lq.plot(r, xi-mean,
    yerr: xi-stderr,
    label: [kNN LS mean $plus.minus sigma slash sqrt({n_mocks})$]),
)
"##,
        r = r,
        xi_a = xi_a,
        xi_m = xi_m,
        xi_se = xi_se,
        n_mocks = result.n_mocks,
    );

    compile_to_svg(&source)
}

/// Render r²ξ(r) comparison.
pub fn render_r2xi_plot(result: &ValidationResult) -> String {
    let r2_xi_analytic: Vec<f64> = result.r_centers.iter()
        .zip(result.xi_analytic.iter())
        .map(|(&r, &xi)| r * r * xi)
        .collect();
    let r2_xi_mean: Vec<f64> = result.r_centers.iter()
        .zip(result.mean_xi.iter())
        .map(|(&r, &xi)| r * r * xi)
        .collect();
    let r2_stderr: Vec<f64> = result.r_centers.iter()
        .zip(result.stderr_xi.iter())
        .map(|(&r, &se)| r * r * se)
        .collect();

    let r = fmt_array(&result.r_centers);
    let r2xi_a = fmt_array(&r2_xi_analytic);
    let r2xi_m = fmt_array(&r2_xi_mean);
    let r2xi_se = fmt_array(&r2_stderr);

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let r2xi-analytic = {r2xi_a}
#let r2xi-mean = {r2xi_m}
#let r2xi-stderr = {r2xi_se}

#lq.diagram(
  title: [$r^2 xi(r)$ Comparison],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$r^2 xi(r)$],
  lq.plot(r, r2xi-analytic,
    label: [Analytic $r^2 xi(r)$],
    stroke: (dash: "dashed", paint: black)),
  lq.plot(r, r2xi-mean,
    yerr: r2xi-stderr,
    label: [kNN LS mean]),
)
"##,
        r = r,
        r2xi_a = r2xi_a,
        r2xi_m = r2xi_m,
        r2xi_se = r2xi_se,
    );

    compile_to_svg(&source)
}

/// Render kNN-CDFs.
pub fn render_cdf_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);
    let cdf_arrays: Vec<String> = result.knn_cdfs.iter().map(|cdf| fmt_array(cdf)).collect();
    let cdfs = format!("({})", cdf_arrays.join(", "));

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}
#let cdfs = {cdfs}

#lq.diagram(
  title: [kNN Empirical CDFs (unique to kNN method)],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$"CDF"_k (r)$],
  ..cdfs.enumerate().map(((k, cdf)) =>
    lq.plot(r, cdf, label: [$k = #(k + 1)$])
  )
)
"##,
        r = r,
        cdfs = cdfs,
    );

    compile_to_svg(&source)
}

/// Render dilution ladder variance.
pub fn render_dilution_plot(result: &ValidationResult) -> String {
    let r = fmt_array(&result.r_centers);
    let mut level_plots = String::new();
    for (level, (xi, var)) in result.dilution_xi.iter()
        .zip(result.dilution_variance.iter())
        .enumerate()
    {
        let xi_arr = fmt_array(xi);
        let stderr: Vec<f64> = var.iter().map(|v| v.sqrt()).collect();
        let se_arr = fmt_array(&stderr);
        let r_ell = 8usize.pow(level as u32);
        let r_char = result.dilution_r_char.get(level).copied().unwrap_or(0.0);
        level_plots.push_str(&format!(
            r#"  lq.plot(r, {xi_arr},
    yerr: {se_arr},
    label: [Level {level} ($R_ell = {r_ell}$, $r_"char" = {r_char:.0}$)]),
"#,
            xi_arr = xi_arr,
            se_arr = se_arr,
            level = level,
            r_ell = r_ell,
            r_char = r_char,
        ));
    }

    let source = format!(
        r##"#set page(width: 16cm, height: 11cm, margin: 5mm)
#set text(font: "New Computer Modern")
#import "@preview/lilaq:0.6.0" as lq

#let r = {r}

#lq.diagram(
  title: [Dilution Ladder $hat(xi)(r) plus.minus sigma$ (model-free variance)],
  xlabel: [$r$ #h(0.3em) $[$h$""^(-1)$ Mpc$]$],
  ylabel: [$xi(r)$],
{level_plots})
"##,
        r = r,
        level_plots = level_plots,
    );

    compile_to_svg(&source)
}
